name: Release

on:
  workflow_call:

jobs:
  release:
    name: Semantic Release
    runs-on: [self-hosted, Linux]
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md
          update-file: VERSION
          allow-initial-development-versions: false
          force-bump-patch-version: false
