name: Release

on:
  workflow_call:
    inputs:
      go_version:
        description: "Go version to use (e.g. '1.24'). Defaults to 1.24."
        required: false
        type: string
        default: "1.24"

jobs:
  release:
    name: Semantic Release
    runs-on: [self-hosted, Linux]
    timeout-minutes: 10
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
          cache: false

      - uses: go-semantic-release/action@v1.24.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md
          update-file: VERSION
          allow-initial-development-versions: false
          force-bump-patch-version: false
